import Mathlib.CategoryTheory.Endomorphism
import QuantumErrorCorrection.BoundedSpreadMonoidal

/-!
# Quantum cellular automata and finite-depth circuits

## Quantum cellular automata

A *quantum cellular automaton* on a quasi-local algebra `A` is an automorphism of `A` in
`BoundedSpreadCat` (see `BoundedSpreadHom.lean`), `QCA A := Aut A`. It is a bounded-spread
`*`-homomorphism with a bounded-spread inverse, and QCAs form a group under composition.
`QCA.ofInverse` builds one from a pair of mutually inverse bounded-spread homomorphisms.
`QCA.HasSpread u l` says both `u` and `u⁻¹` have spread `l` (the light-cone radius). Every QCA
has some finite spread, and this spread is monotone in `l`, `0` for the identity, additive under
products, and unchanged by inversion.

## Finite-depth circuits

A *layer of range `r`* (`QCA.IsLayer u r`) is one time step of a circuit of gates of diameter at
most `r` on disjoint blocks. Formally, there is a partition of the sites into blocks of diameter
at most `r` such that `u` and `u⁻¹` map the algebra of every union of blocks into itself
(`BoundedSpreadHom.PreservesRegion`). Layers are closed under inversion and increasing the
range, and include the identity. `QCA.IsCircuit u r d` says `u` is a product of `d` layers of
range `r`, and `QCA.IsCircuit.hasSpread` is the light-cone bound: such a `u` has spread at most
`d * r`. `QCA.circuitSubgroup A` is the subgroup generated by all layers, and
`QCA.mem_circuitSubgroup_iff` identifies it with the finite-depth circuits of finite range.

## Stacking

Stacking systems (the monoidal structure of `BoundedSpreadCat`, `BoundedSpreadMonoidal.lean`)
stacks QCAs: `QCA.stackMonoidHom : QCA A × QCA B →* QCA (A ⊗ B)`, `(u, v) ↦ u ⊗ v`. Stacking
QCAs of spreads `l` and `l'` gives spread `max l l'` (`QCA.HasSpread.stack`). Stacking a layer
with the identity is a layer with the same blocks (`QCA.IsLayer.stack_one`,
`QCA.IsLayer.one_stack`), so stacked circuits are circuits (`QCA.stack_mem_circuitSubgroup`).
-/

noncomputable section

open CategoryTheory NNReal RegionCat

universe u

variable {X : Type u} [DecidableEq X] [MetricSpace X] [FiniteClosedBalls X]
variable {𝕜 : Type u} [CommRing 𝕜] [StarRing 𝕜]

/-! ### Quantum cellular automata -/

/-- A *quantum cellular automaton* on the quasi-local algebra `A`: an automorphism of `A` in
`BoundedSpreadCat`. Concretely, it is a bounded-spread homomorphism `A ⟶ A` together with a
bounded-spread homomorphism `A ⟶ A` inverse to it. Each composite is the identity once both
are regarded inside a large enough neighborhood. Under composition these form a group
(`CategoryTheory.Aut`); `u * v` is "first `v`, then `u`". -/
abbrev QCA (A : BoundedSpreadCat X 𝕜) := Aut A

namespace QCA

open BoundedSpreadCat

variable {A : BoundedSpreadCat X 𝕜} {l l' : ℝ≥0}

/-- Build a QCA from a spread-`l` homomorphism `α` and a spread-`l'` homomorphism `β` that are
mutually inverse up to weakening, i.e. `β_{N_l S} ∘ α_S` and `α_{N_l' S} ∘ β_S` are the
inclusions `A(S) ↪ A(N_(l+l') S)`. -/
def ofInverse (α : BoundedSpreadHom l A.toQuasiLocalAlgebra A.toQuasiLocalAlgebra)
    (β : BoundedSpreadHom l' A.toQuasiLocalAlgebra A.toQuasiLocalAlgebra)
    (hαβ : α.comp β = (BoundedSpreadHom.id _).weaken (zero_le : (0 : ℝ≥0) ≤ l + l'))
    (hβα : β.comp α = (BoundedSpreadHom.id _).weaken (zero_le : (0 : ℝ≥0) ≤ l' + l)) :
    QCA A where
  hom := homMk α
  inv := homMk β
  hom_inv_id := by rw [← homMk_comp, hαβ, homMk_weaken, homMk_id]
  inv_hom_id := by rw [← homMk_comp, hβα, homMk_weaken, homMk_id]

@[simp] theorem ofInverse_hom (α : BoundedSpreadHom l A.toQuasiLocalAlgebra A.toQuasiLocalAlgebra)
    (β : BoundedSpreadHom l' A.toQuasiLocalAlgebra A.toQuasiLocalAlgebra) (hαβ hβα) :
    (ofInverse α β hαβ hβα).hom = homMk α := rfl

@[simp] theorem ofInverse_inv (α : BoundedSpreadHom l A.toQuasiLocalAlgebra A.toQuasiLocalAlgebra)
    (β : BoundedSpreadHom l' A.toQuasiLocalAlgebra A.toQuasiLocalAlgebra) (hαβ hβα) :
    (ofInverse α β hαβ hβα).inv = homMk β := rfl

/-- A QCA has *spread at most `l`* (its light-cone radius) when both it and its inverse are
represented by homomorphisms of spread `l`. -/
def HasSpread (u : QCA A) (l : ℝ≥0) : Prop :=
  BoundedSpreadCat.HasSpread u.hom l ∧ BoundedSpreadCat.HasSpread u.inv l

/-- Every QCA has some finite spread. -/
theorem exists_hasSpread (u : QCA A) : ∃ l, u.HasSpread l := by
  obtain ⟨l, α, hα⟩ := homMk_surjective u.hom
  obtain ⟨l', β, hβ⟩ := homMk_surjective u.inv
  exact ⟨max l l', (hα ▸ hasSpread_homMk α).mono (le_max_left l l'),
    (hβ ▸ hasSpread_homMk β).mono (le_max_right l l')⟩

theorem HasSpread.mono {u : QCA A} (hu : u.HasSpread l) (h : l ≤ l') : u.HasSpread l' :=
  ⟨hu.1.mono h, hu.2.mono h⟩

theorem hasSpread_one (A : BoundedSpreadCat X 𝕜) : (1 : QCA A).HasSpread 0 :=
  ⟨hasSpread_id A, hasSpread_id A⟩

/-- Spreads add under composition of QCAs. -/
theorem HasSpread.mul {u v : QCA A} (hu : u.HasSpread l) (hv : v.HasSpread l') :
    (u * v).HasSpread (l + l') :=
  ⟨add_comm l' l ▸ hv.1.comp hu.1, hu.2.comp hv.2⟩

theorem HasSpread.inv {u : QCA A} (hu : u.HasSpread l) : u⁻¹.HasSpread l :=
  ⟨hu.2, hu.1⟩

@[simp] theorem hasSpread_inv_iff {u : QCA A} : u⁻¹.HasSpread l ↔ u.HasSpread l :=
  ⟨fun h => h.inv, fun h => h.inv⟩

end QCA

/-! ### Finite-depth circuits -/

namespace BoundedSpreadHom

variable {l l' : ℝ≥0} {𝒜 𝒜' : QuasiLocalAlgebra X 𝕜}

/-- `α` maps observables on the region `B` to observables on `B` itself, rather than on its whole
`l`-neighborhood: `α_B` factors through `𝒜'(B) ↪ 𝒜'(metricNbhd l B)`. -/
def PreservesRegion (α : BoundedSpreadHom l 𝒜 𝒜') (B : RegionCat X) : Prop :=
  ∃ γ : 𝒜.net.obj B ⟶ 𝒜'.net.obj B,
    α.app B = γ ≫ 𝒜'.net.map (homOfSubset (subset_metricNbhd l B))

theorem PreservesRegion.weaken {α : BoundedSpreadHom l 𝒜 𝒜'} {B : RegionCat X}
    (hα : α.PreservesRegion B) (h : l ≤ l') : (α.weaken h).PreservesRegion B :=
  let ⟨γ, hγ⟩ := hα
  ⟨γ, by rw [weaken_app, hγ, Category.assoc, ← Functor.map_comp]; rfl⟩

theorem preservesRegion_id (𝒜 : QuasiLocalAlgebra X 𝕜) (B : RegionCat X) :
    (id 𝒜).PreservesRegion B :=
  ⟨𝟙 _, by rw [id_app, Category.id_comp]⟩

end BoundedSpreadHom

namespace QCA

open BoundedSpreadCat BoundedSpreadHom

variable {A : BoundedSpreadCat X 𝕜} {r r' : ℝ≥0}

/-- `u` is a *layer of range `r`*: a single time step of a circuit made of gates of diameter at
most `r` acting on disjoint blocks. The sites are partitioned into `blocks`, each of diameter at
most `r`, and `u` and `u⁻¹` have spread-`r` representatives that map the algebra of every union
of blocks into itself. For a tensor-product net, where `A(B)` is generated by the algebras of the
blocks in `B`, this is exactly a product of automorphisms of the individual blocks (the gates). -/
def IsLayer (u : QCA A) (r : ℝ≥0) : Prop :=
  ∃ blocks : Setoid X, (∀ x y, blocks x y → dist x y ≤ r) ∧
    ∃ α β : BoundedSpreadHom r A.toQuasiLocalAlgebra A.toQuasiLocalAlgebra,
      homMk α = u.hom ∧ homMk β = u.inv ∧
        ∀ B : RegionCat X, (∀ x ∈ B.carrier, ∀ y, blocks x y → y ∈ B.carrier) →
          α.PreservesRegion B ∧ β.PreservesRegion B

theorem IsLayer.hasSpread {u : QCA A} (hu : u.IsLayer r) : u.HasSpread r :=
  let ⟨_, _, α, β, hα, hβ, _⟩ := hu
  ⟨⟨α, hα⟩, ⟨β, hβ⟩⟩

theorem IsLayer.mono {u : QCA A} (hu : u.IsLayer r) (h : r ≤ r') : u.IsLayer r' :=
  let ⟨blocks, hd, α, β, hα, hβ, hB⟩ := hu
  ⟨blocks, fun x y hxy => (hd x y hxy).trans (by exact_mod_cast h), α.weaken h, β.weaken h,
    by rw [homMk_weaken, hα], by rw [homMk_weaken, hβ],
    fun B hBs => ⟨(hB B hBs).1.weaken h, (hB B hBs).2.weaken h⟩⟩

theorem IsLayer.inv {u : QCA A} (hu : u.IsLayer r) : u⁻¹.IsLayer r :=
  let ⟨blocks, hd, α, β, hα, hβ, hB⟩ := hu
  ⟨blocks, hd, β, α, hβ, hα, fun B hBs => (hB B hBs).symm⟩

/-- The identity is a layer of any range: every block is a single site. -/
theorem isLayer_one (A : BoundedSpreadCat X 𝕜) (r : ℝ≥0) : (1 : QCA A).IsLayer r :=
  ⟨Setoid.ker (fun x : X => x),
    fun x y hxy => by rw [Setoid.ker_def.1 hxy, dist_self]; exact r.2,
    (BoundedSpreadHom.id _).weaken (zero_le : (0 : ℝ≥0) ≤ r),
    (BoundedSpreadHom.id _).weaken (zero_le : (0 : ℝ≥0) ≤ r),
    by rw [homMk_weaken, homMk_id]; rfl, by rw [homMk_weaken, homMk_id]; rfl,
    fun B _ => ⟨(preservesRegion_id _ B).weaken _, (preservesRegion_id _ B).weaken _⟩⟩

/-- `u` is implemented by a *circuit of range `r` and depth `d`*: a product of `d` layers of
range `r`. -/
def IsCircuit (u : QCA A) (r : ℝ≥0) (d : ℕ) : Prop :=
  ∃ L : List (QCA A), L.length = d ∧ (∀ v ∈ L, v.IsLayer r) ∧ L.prod = u

/-- The light-cone bound: a circuit of range `r` and depth `d` has spread at most `d * r`. -/
theorem IsCircuit.hasSpread {u : QCA A} {d : ℕ} (hu : u.IsCircuit r d) :
    u.HasSpread (d * r) := by
  obtain ⟨L, rfl, hL, rfl⟩ := hu
  induction L with
  | nil => simpa using hasSpread_one A
  | cons v L ih =>
    have hlen : ((v :: L).length : ℝ≥0) * r = r + L.length * r := by
      rw [List.length_cons]
      push_cast
      ring
    rw [hlen, List.prod_cons]
    exact (hL v List.mem_cons_self).hasSpread.mul
      (ih fun w hw => hL w (List.mem_cons_of_mem v hw))

/-- The *circuit subgroup*: the QCAs generated by layers of arbitrary (finite) range. -/
def circuitSubgroup (A : BoundedSpreadCat X 𝕜) : Subgroup (QCA A) :=
  Subgroup.closure {u | ∃ r, u.IsLayer r}

/-- A QCA lies in the circuit subgroup exactly when it is a finite-depth circuit of some finite
range. -/
theorem mem_circuitSubgroup_iff {u : QCA A} :
    u ∈ circuitSubgroup A ↔ ∃ r d, u.IsCircuit r d := by
  constructor
  · intro hu
    induction hu using Subgroup.closure_induction with
    | mem v hv =>
      obtain ⟨r, hv⟩ := hv
      exact ⟨r, 1, [v], rfl, by simpa using hv, List.prod_singleton⟩
    | one => exact ⟨0, 0, [], rfl, by simp, List.prod_nil⟩
    | mul v w _ _ hv hw =>
      obtain ⟨r, d, L, hLd, hL, rfl⟩ := hv
      obtain ⟨r', d', L', hLd', hL', rfl⟩ := hw
      refine ⟨max r r', d + d', L ++ L', by simp [hLd, hLd'], fun x hx => ?_, List.prod_append⟩
      rcases List.mem_append.1 hx with hx | hx
      · exact (hL x hx).mono (le_max_left r r')
      · exact (hL' x hx).mono (le_max_right r r')
    | inv v _ hv =>
      obtain ⟨r, d, L, hLd, hL, rfl⟩ := hv
      refine ⟨r, d, (L.map fun x => x⁻¹).reverse, by simp [hLd], fun x hx => ?_,
        (List.prod_inv_reverse L).symm⟩
      obtain ⟨y, hy, rfl⟩ := List.mem_map.1 (List.mem_reverse.1 hx)
      exact (hL y hy).inv
  · rintro ⟨r, d, L, -, hL, rfl⟩
    refine (circuitSubgroup A).list_prod_mem fun v hv => Subgroup.subset_closure ?_
    exact ⟨r, hL v hv⟩

theorem IsCircuit.mem_circuitSubgroup {u : QCA A} {d : ℕ} (hu : u.IsCircuit r d) :
    u ∈ circuitSubgroup A :=
  mem_circuitSubgroup_iff.2 ⟨r, d, hu⟩

end QCA

/-! ### Stacking -/

namespace QCA

open MonoidalCategory BoundedSpreadCat

variable {A B : BoundedSpreadCat X 𝕜} {l l' : ℝ≥0}

variable (A B) in
/-- Stacking QCAs: `(u, v) ↦ u ⊗ v`, a group homomorphism into the QCAs of the stacked
system. -/
def stackMonoidHom : QCA A × QCA B →* QCA (A ⊗ B) where
  toFun p := p.1 ⊗ᵢ p.2
  map_one' := Aut.ext (id_tensorHom_id A B)
  map_mul' p q := Aut.ext (tensorHom_comp_tensorHom q.1.hom q.2.hom p.1.hom p.2.hom).symm

@[simp] theorem stackMonoidHom_hom (u : QCA A) (v : QCA B) :
    (stackMonoidHom A B (u, v)).hom = u.hom ⊗ₘ v.hom :=
  rfl

/-- Stacking QCAs of spreads `l` and `l'` gives a QCA of spread `max l l'`. -/
theorem HasSpread.stack {u : QCA A} {v : QCA B} (hu : u.HasSpread l) (hv : v.HasSpread l') :
    (stackMonoidHom A B (u, v)).HasSpread (max l l') :=
  ⟨hu.1.stackHom hv.1, hu.2.stackHom hv.2⟩

open BoundedSpreadHom in
private lemma preservesRegion_tensor_id {A A' : BoundedSpreadCat X 𝕜} {r : ℝ≥0}
    {α : BoundedSpreadHom r A.1 A'.1} {R : RegionCat X} (hα : α.PreservesRegion R) :
    (tensorBSH (B := B) α ((BoundedSpreadHom.id B.1).weaken (zero_le : (0 : ℝ≥0) ≤ r))).PreservesRegion
      R := by
  obtain ⟨γ, hγ⟩ := hα
  refine ⟨γ ⊗ₘ 𝟙 _, ?_⟩
  rw [tensorBSH_app, hγ, weaken_app, id_app, net_map_comp_homOfSubset]
  refine Eq.trans ?_ (tensorHom_comp_tensorHom _ _ _ _).symm
  rw [Category.id_comp]

open BoundedSpreadHom in
private lemma preservesRegion_id_tensor {B B' : BoundedSpreadCat X 𝕜} {r : ℝ≥0}
    {β : BoundedSpreadHom r B.1 B'.1} {R : RegionCat X} (hβ : β.PreservesRegion R) :
    (tensorBSH (A := A) ((BoundedSpreadHom.id A.1).weaken (zero_le : (0 : ℝ≥0) ≤ r)) β).PreservesRegion
      R := by
  obtain ⟨γ, hγ⟩ := hβ
  refine ⟨𝟙 _ ⊗ₘ γ, ?_⟩
  rw [tensorBSH_app, hγ, weaken_app, id_app, net_map_comp_homOfSubset]
  refine Eq.trans ?_ (tensorHom_comp_tensorHom _ _ _ _).symm
  rw [Category.id_comp]

/-- Stacking a layer with the identity gives a layer of the same range, with the same blocks. -/
theorem IsLayer.stack_one {u : QCA A} {r : ℝ≥0} (hu : u.IsLayer r) :
    (stackMonoidHom A B (u, 1)).IsLayer r := by
  obtain ⟨blocks, hd, α, β, hα, hβ, hR⟩ := hu
  refine ⟨blocks, hd, tensorBSH α ((BoundedSpreadHom.id B.1).weaken (zero_le : (0 : ℝ≥0) ≤ r)),
    tensorBSH β ((BoundedSpreadHom.id B.1).weaken (zero_le : (0 : ℝ≥0) ≤ r)), ?_, ?_,
    fun R hRs => ⟨preservesRegion_tensor_id (hR R hRs).1, preservesRegion_tensor_id (hR R hRs).2⟩⟩
  · rw [← homMk_stackHom, homMk_weaken, homMk_id, hα]
    rfl
  · rw [← homMk_stackHom, homMk_weaken, homMk_id, hβ]
    rfl

/-- Stacking the identity with a layer gives a layer of the same range, with the same blocks. -/
theorem IsLayer.one_stack {v : QCA B} {r : ℝ≥0} (hv : v.IsLayer r) :
    (stackMonoidHom A B (1, v)).IsLayer r := by
  obtain ⟨blocks, hd, α, β, hα, hβ, hR⟩ := hv
  refine ⟨blocks, hd, tensorBSH ((BoundedSpreadHom.id A.1).weaken (zero_le : (0 : ℝ≥0) ≤ r)) α,
    tensorBSH ((BoundedSpreadHom.id A.1).weaken (zero_le : (0 : ℝ≥0) ≤ r)) β, ?_, ?_,
    fun R hRs => ⟨preservesRegion_id_tensor (hR R hRs).1, preservesRegion_id_tensor (hR R hRs).2⟩⟩
  · rw [← homMk_stackHom, homMk_weaken, homMk_id, hα]
    rfl
  · rw [← homMk_stackHom, homMk_weaken, homMk_id, hβ]
    rfl

/-- Stacking finite-depth circuits gives a finite-depth circuit: `stackMonoidHom` maps
`circuitSubgroup A × circuitSubgroup B` into `circuitSubgroup (A ⊗ B)`. -/
theorem stack_mem_circuitSubgroup {u : QCA A} {v : QCA B} (hu : u ∈ circuitSubgroup A)
    (hv : v ∈ circuitSubgroup B) : stackMonoidHom A B (u, v) ∈ circuitSubgroup (A ⊗ B) := by
  have hsplit : ((u, v) : QCA A × QCA B) = (u, 1) * (1, v) := by simp
  rw [hsplit, map_mul]
  refine mul_mem ?_ ?_
  · have h : circuitSubgroup A ≤
        (circuitSubgroup (A ⊗ B)).comap ((stackMonoidHom A B).comp (MonoidHom.inl _ _)) := by
      rw [circuitSubgroup, Subgroup.closure_le]
      rintro w ⟨r, hw⟩
      exact Subgroup.subset_closure ⟨r, hw.stack_one⟩
    exact h hu
  · have h : circuitSubgroup B ≤
        (circuitSubgroup (A ⊗ B)).comap ((stackMonoidHom A B).comp (MonoidHom.inr _ _)) := by
      rw [circuitSubgroup, Subgroup.closure_le]
      rintro w ⟨r, hw⟩
      exact Subgroup.subset_closure ⟨r, hw.one_stack⟩
    exact h hv

end QCA

end
