import Mathlib.GroupTheory.NoncommPiCoprod
import Mathlib.Data.ZMod.Basic

/-!
# From commuting involutions to a `(ZMod 2)^N` action

Given a family `q : Fin N → Equiv.Perm V` of pairwise-commuting involutions (`q i * q i = 1`),
this file builds the monoid homomorphism `(∀ i, Multiplicative (ZMod 2)) →* Equiv.Perm V`
sending the `i`-th generator to `q i`, together with the induced `MulAction` of the group
`∀ i, Multiplicative (ZMod 2)` (i.e. `(ZMod 2)^N`, written multiplicatively) on `V`.
-/

namespace CommutingInvolutions

variable {V : Type*} {N : ℕ} (q : Fin N → Equiv.Perm V)

private lemma pow_val_add {M : Type*} [Monoid M] {x : M} (hx : x * x = 1) (a b : ZMod 2) :
    x ^ (a + b).val = x ^ a.val * x ^ b.val := by
  have hx2 : x ^ 2 = 1 := by rw [sq]; exact hx
  rw [← pow_add, ZMod.val_add]
  conv_rhs => rw [← Nat.mod_add_div (a.val + b.val) 2]
  rw [pow_add, pow_mul, hx2, one_pow, mul_one]

/-- The monoid homomorphism `Multiplicative (ZMod 2) →* Equiv.Perm V` sending the generator to
`q i`, given that `q i` is an involution. -/
def genHom (i : Fin N) (hsq : q i * q i = 1) : Multiplicative (ZMod 2) →* Equiv.Perm V where
  toFun ε := q i ^ (Multiplicative.toAdd ε).val
  map_one' := by simp
  map_mul' a b := by
    show q i ^ (Multiplicative.toAdd (a * b)).val = _
    rw [toAdd_mul]
    exact pow_val_add hsq _ _

@[simp] lemma genHom_apply_ofAdd (i : Fin N) (hsq : q i * q i = 1) (a : ZMod 2) :
    genHom q i hsq (Multiplicative.ofAdd a) = q i ^ a.val := rfl

variable {q}

/-- The `(ZMod 2)^N` action generated by a family of pairwise-commuting involutions `q i`,
packaged as a monoid homomorphism from `∀ i, Multiplicative (ZMod 2)`. -/
def toMonoidHom (hsq : ∀ i, q i * q i = 1) (hcomm : Pairwise fun i j => Commute (q i) (q j)) :
    (Fin N → Multiplicative (ZMod 2)) →* Equiv.Perm V :=
  MonoidHom.noncommPiCoprod (fun i => genHom q i (hsq i))
    (fun _i _j hij _ _ => (hcomm hij).pow_pow _ _)

/-- The induced action of `(ZMod 2)^N` (written as `∀ i, Multiplicative (ZMod 2)`) on `V`. -/
@[instance_reducible] def toMulAction (hsq : ∀ i, q i * q i = 1) (hcomm : Pairwise fun i j => Commute (q i) (q j)) :
    MulAction (Fin N → Multiplicative (ZMod 2)) V where
  smul g x := toMonoidHom hsq hcomm g x
  one_smul x := by
    show toMonoidHom hsq hcomm 1 x = x
    rw [map_one]; rfl
  mul_smul g h x := by
    show toMonoidHom hsq hcomm (g * h) x = toMonoidHom hsq hcomm g (toMonoidHom hsq hcomm h x)
    rw [map_mul]; rfl

end CommutingInvolutions
